// Curated country → universities lists for the Calendar's university picker.
// Not exhaustive — every country also offers an "Other…" option (added in the UI)
// so a student can type an unlisted institution; the AI fills dates from the name.

export const UNIVERSITIES = {
  "New Zealand": [
    "University of Auckland",
    "Auckland University of Technology",
    "University of Waikato",
    "Massey University",
    "Victoria University of Wellington",
    "University of Canterbury",
    "Lincoln University",
    "University of Otago",
  ],
  Australia: [
    "University of Sydney",
    "University of New South Wales",
    "University of Melbourne",
    "Monash University",
    "Australian National University",
    "University of Queensland",
    "University of Western Australia",
    "University of Adelaide",
    "University of Technology Sydney",
    "RMIT University",
    "Queensland University of Technology",
    "Macquarie University",
  ],
  "United Kingdom": [
    "University of Oxford",
    "University of Cambridge",
    "Imperial College London",
    "University College London",
    "University of Edinburgh",
    "University of Manchester",
    "King's College London",
    "London School of Economics",
    "University of Bristol",
    "University of Warwick",
    "University of Glasgow",
    "University of Leeds",
    "University of Nottingham",
    "University of Birmingham",
    "Durham University",
  ],
  Ireland: [
    "Trinity College Dublin",
    "University College Dublin",
    "University College Cork",
    "University of Galway",
    "Dublin City University",
    "Maynooth University",
    "University of Limerick",
  ],
  "United States": [
    "Harvard University",
    "Massachusetts Institute of Technology",
    "Stanford University",
    "University of California, Berkeley",
    "University of California, Los Angeles",
    "Yale University",
    "Princeton University",
    "Columbia University",
    "University of Michigan",
    "New York University",
    "University of Texas at Austin",
    "University of Washington",
    "Georgia Institute of Technology",
    "University of Illinois Urbana-Champaign",
    "Cornell University",
  ],
  Canada: [
    "University of Toronto",
    "University of British Columbia",
    "McGill University",
    "University of Waterloo",
    "University of Alberta",
    "McMaster University",
    "Université de Montréal",
    "University of Calgary",
    "Queen's University",
    "Western University",
  ],
  "South Africa": [
    "University of Cape Town",
    "University of the Witwatersrand",
    "Stellenbosch University",
    "University of Pretoria",
    "University of KwaZulu-Natal",
    "University of Johannesburg",
  ],
  India: [
    "Indian Institute of Technology Bombay",
    "Indian Institute of Technology Delhi",
    "Indian Institute of Technology Madras",
    "Indian Institute of Science",
    "University of Delhi",
    "Indian Institute of Technology Kanpur",
    "Jawaharlal Nehru University",
    "Anna University",
  ],
  Singapore: [
    "National University of Singapore",
    "Nanyang Technological University",
    "Singapore Management University",
    "Singapore University of Technology and Design",
  ],
};

export const COUNTRIES = Object.keys(UNIVERSITIES);
